// 상품 데이터 — 모든 컴포넌트에서 import하여 사용
// 하드코딩 금지, 반드시 이 파일에서 관리

export const categories = [
  { id: 'cake',    name: '케이크',   icon: '🎂' },
  { id: 'cookie',  name: '쿠키',     icon: '🍪' },
  { id: 'macaron', name: '마카롱',   icon: '🧁' },
  { id: 'bread',   name: '빵',       icon: '🥐' },
  { id: 'drink',   name: '음료',     icon: '☕' },
  { id: 'gift',    name: '선물세트', icon: '🎁' },
]

export const products = [
  {
    id: 'prod-001',
    name: '딸기 생크림 케이크',
    nameEn: 'Strawberry Fresh Cream Cake',
    category: 'cake',
    price: 38000,
    salePrice: null,
    description: '신선한 딸기와 부드러운 생크림의 조화',
    detailDescription: '매일 아침 공수되는 국내산 딸기와 프랑스산 생크림으로 만든 프리미엄 케이크입니다. 촉촉한 시트 사이사이에 신선한 딸기가 가득합니다.',
    images: ['/images/products/strawberry-cake.jpg'],
    options: [
      { name: '미니 (1호)', priceAdd: 0 },
      { name: '레귤러 (2호)', priceAdd: 10000 },
      { name: '라지 (3호)', priceAdd: 22000 },
    ],
    tags: ['인기', '베스트'],
    badge: 'BEST',
    stock: 50,
    rating: 4.8,
    reviewCount: 124,
    isNew: false,
    allergens: ['밀', '우유', '달걀'],
    storageMethod: '냉장 보관 (0~5°C)',
    shelfLife: '제조일로부터 3일',
  },
  {
    id: 'prod-002',
    name: '다크 초콜릿 가나슈 케이크',
    nameEn: 'Dark Chocolate Ganache Cake',
    category: 'cake',
    price: 42000,
    salePrice: 38000,
    description: '진한 벨기에 초콜릿의 깊은 풍미',
    detailDescription: '벨기에산 카카오 70% 초콜릿으로 만든 가나슈 크림과 촉촉한 초콜릿 시트의 완벽한 조합입니다.',
    images: ['/images/products/chocolate-cake.jpg'],
    options: [
      { name: '미니 (1호)', priceAdd: 0 },
      { name: '레귤러 (2호)', priceAdd: 12000 },
    ],
    tags: ['인기'],
    badge: 'SALE',
    stock: 30,
    rating: 4.9,
    reviewCount: 89,
    isNew: false,
    allergens: ['밀', '우유', '달걀', '대두'],
    storageMethod: '냉장 보관 (0~5°C)',
    shelfLife: '제조일로부터 5일',
  },
  {
    id: 'prod-003',
    name: '얼그레이 마카롱 세트',
    nameEn: 'Earl Grey Macaron Set',
    category: 'macaron',
    price: 24000,
    salePrice: null,
    description: '향긋한 얼그레이 크림이 가득한 마카롱 6개입',
    detailDescription: '프랑스 전통 제법으로 구운 쫀득한 꼬끄에 얼그레이 향이 은은한 버터크림을 샌드한 프리미엄 마카롱입니다.',
    images: ['/images/products/earl-grey-macaron.jpg'],
    options: [
      { name: '6개입', priceAdd: 0 },
      { name: '12개입', priceAdd: 20000 },
    ],
    tags: ['베스트'],
    badge: 'BEST',
    stock: 80,
    rating: 4.7,
    reviewCount: 203,
    isNew: false,
    allergens: ['달걀', '우유', '아몬드'],
    storageMethod: '냉장 보관 (0~5°C)',
    shelfLife: '제조일로부터 7일',
  },
  {
    id: 'prod-004',
    name: '솔티드 카라멜 쿠키',
    nameEn: 'Salted Caramel Cookie',
    category: 'cookie',
    price: 15000,
    salePrice: null,
    description: '바삭하면서도 촉촉한 솔티드 카라멜 쿠키',
    detailDescription: '프랑스 게랑드 소금과 수제 카라멜로 만든 쿠키입니다. 겉은 바삭하고 속은 촉촉한 식감이 매력적입니다.',
    images: ['/images/products/salted-caramel-cookie.jpg'],
    options: [
      { name: '4개입', priceAdd: 0 },
      { name: '8개입', priceAdd: 12000 },
    ],
    tags: [],
    badge: null,
    stock: 100,
    rating: 4.6,
    reviewCount: 67,
    isNew: true,
    allergens: ['밀', '우유', '달걀'],
    storageMethod: '실온 보관 (서늘한 곳)',
    shelfLife: '제조일로부터 14일',
  },
  {
    id: 'prod-005',
    name: '레몬 파운드 케이크',
    nameEn: 'Lemon Pound Cake',
    category: 'cake',
    price: 22000,
    salePrice: null,
    description: '상큼한 레몬 글레이즈의 클래식 파운드 케이크',
    detailDescription: '이탈리아 아말피 해안의 레몬즙과 제스트를 듬뿍 넣은 촉촉한 파운드 케이크에 새콤달콤한 레몬 글레이즈를 입혔습니다.',
    images: ['/images/products/lemon-pound.jpg'],
    options: [
      { name: '레귤러', priceAdd: 0 },
    ],
    tags: [],
    badge: 'NEW',
    stock: 45,
    rating: 4.5,
    reviewCount: 32,
    isNew: true,
    allergens: ['밀', '우유', '달걀'],
    storageMethod: '실온 보관 (서늘한 곳)',
    shelfLife: '제조일로부터 7일',
  },
  {
    id: 'prod-006',
    name: '피스타치오 크루아상',
    nameEn: 'Pistachio Croissant',
    category: 'bread',
    price: 6500,
    salePrice: null,
    description: '고소한 피스타치오 크림이 가득한 크루아상',
    detailDescription: '72시간 저온 발효한 크루아상에 이탈리아산 피스타치오 크림을 듬뿍 채우고 피스타치오 분태를 토핑했습니다.',
    images: ['/images/products/pistachio-croissant.jpg'],
    options: [
      { name: '1개', priceAdd: 0 },
      { name: '3개 세트', priceAdd: 12000 },
    ],
    tags: ['인기'],
    badge: null,
    stock: 60,
    rating: 4.9,
    reviewCount: 156,
    isNew: false,
    allergens: ['밀', '우유', '달걀', '견과류'],
    storageMethod: '실온 보관 (당일 섭취 권장)',
    shelfLife: '당일',
  },
  {
    id: 'prod-007',
    name: '로즈 라즈베리 마카롱 세트',
    nameEn: 'Rose Raspberry Macaron Set',
    category: 'macaron',
    price: 28000,
    salePrice: 24000,
    description: '장미향과 라즈베리의 로맨틱한 조합',
    detailDescription: '다마스크 로즈 에센스와 프랑스산 라즈베리 퓨레로 만든 크림을 가득 채운 프리미엄 마카롱 세트입니다.',
    images: ['/images/products/rose-raspberry-macaron.jpg'],
    options: [
      { name: '6개입', priceAdd: 0 },
      { name: '12개입', priceAdd: 22000 },
    ],
    tags: [],
    badge: 'SALE',
    stock: 40,
    rating: 4.8,
    reviewCount: 91,
    isNew: false,
    allergens: ['달걀', '우유', '아몬드'],
    storageMethod: '냉장 보관 (0~5°C)',
    shelfLife: '제조일로부터 7일',
  },
  {
    id: 'prod-008',
    name: '말차 롤케이크',
    nameEn: 'Matcha Roll Cake',
    category: 'cake',
    price: 28000,
    salePrice: null,
    description: '교토 우지 말차로 만든 프리미엄 롤케이크',
    detailDescription: '일본 교토 우지 지역의 최상급 말차를 사용한 스폰지에 부드러운 생크림을 돌돌 말아 만든 롤케이크입니다.',
    images: ['/images/products/matcha-roll.jpg'],
    options: [
      { name: '레귤러', priceAdd: 0 },
    ],
    tags: [],
    badge: 'NEW',
    stock: 35,
    rating: 4.7,
    reviewCount: 45,
    isNew: true,
    allergens: ['밀', '우유', '달걀'],
    storageMethod: '냉장 보관 (0~5°C)',
    shelfLife: '제조일로부터 3일',
  },
  {
    id: 'prod-009',
    name: '바닐라 빈 마들렌',
    nameEn: 'Vanilla Bean Madeleine',
    category: 'cookie',
    price: 12000,
    salePrice: null,
    description: '마다가스카르 바닐라 빈이 들어간 정통 마들렌',
    detailDescription: '마다가스카르산 바닐라 빈을 직접 갈아 넣어 풍부한 바닐라 향이 특징인 프랑스 정통 마들렌입니다.',
    images: ['/images/products/vanilla-madeleine.jpg'],
    options: [
      { name: '6개입', priceAdd: 0 },
      { name: '12개입', priceAdd: 10000 },
    ],
    tags: [],
    badge: null,
    stock: 70,
    rating: 4.4,
    reviewCount: 58,
    isNew: false,
    allergens: ['밀', '우유', '달걀'],
    storageMethod: '실온 보관 (서늘한 곳)',
    shelfLife: '제조일로부터 10일',
  },
  {
    id: 'prod-010',
    name: '시그니처 블렌드 커피',
    nameEn: 'Signature Blend Coffee',
    category: 'drink',
    price: 18000,
    salePrice: null,
    description: '디저트와 완벽한 페어링을 위한 시그니처 원두',
    detailDescription: '에티오피아 예가체프와 콜롬비아 수프리모를 블렌딩한 원두입니다. 디저트의 달콤함과 조화로운 산미가 특징입니다.',
    images: ['/images/products/signature-coffee.jpg'],
    options: [
      { name: '200g', priceAdd: 0 },
      { name: '500g', priceAdd: 25000 },
    ],
    tags: [],
    badge: null,
    stock: 200,
    rating: 4.6,
    reviewCount: 73,
    isNew: false,
    allergens: [],
    storageMethod: '실온 보관 (밀봉, 서늘한 곳)',
    shelfLife: '로스팅일로부터 30일',
  },
  {
    id: 'prod-011',
    name: '프리미엄 디저트 선물세트 A',
    nameEn: 'Premium Dessert Gift Set A',
    category: 'gift',
    price: 55000,
    salePrice: 48000,
    description: '마카롱 6종 + 마들렌 4종 프리미엄 구성',
    detailDescription: '가장 인기 있는 마카롱 6종과 마들렌 4종을 고급 선물 박스에 담았습니다. 특별한 날, 소중한 분께 전하세요.',
    images: ['/images/products/gift-set-a.jpg'],
    options: [
      { name: '기본 구성', priceAdd: 0 },
    ],
    tags: ['인기', '선물'],
    badge: 'BEST',
    stock: 25,
    rating: 4.9,
    reviewCount: 112,
    isNew: false,
    allergens: ['밀', '우유', '달걀', '아몬드'],
    storageMethod: '냉장 보관 (0~5°C)',
    shelfLife: '제조일로부터 5일',
  },
  {
    id: 'prod-012',
    name: '크렘 브륄레',
    nameEn: 'Crème Brûlée',
    category: 'cake',
    price: 8500,
    salePrice: null,
    description: '바삭한 카라멜 위의 부드러운 커스터드',
    detailDescription: '프랑스 전통 레시피로 만든 크렘 브륄레입니다. 토치로 직접 카라멜라이즈한 바삭한 설탕 층 아래 실크처럼 부드러운 커스터드가 있습니다.',
    images: ['/images/products/creme-brulee.jpg'],
    options: [
      { name: '1개', priceAdd: 0 },
      { name: '3개 세트', priceAdd: 16000 },
    ],
    tags: [],
    badge: 'NEW',
    stock: 40,
    rating: 4.8,
    reviewCount: 28,
    isNew: true,
    allergens: ['우유', '달걀'],
    storageMethod: '냉장 보관 (0~5°C)',
    shelfLife: '제조일로부터 3일',
  },
]

// 리뷰 데이터 — 메인 페이지 미리보기용
export const reviews = [
  {
    id: 'rev-001',
    productId: 'prod-001',
    productName: '딸기 생크림 케이크',
    userName: '김**',
    rating: 5,
    content: '생일 케이크로 주문했는데 정말 예쁘고 맛있었어요! 딸기가 정말 신선하고 크림도 달지 않아서 좋았습니다.',
    date: '2024-12-15',
  },
  {
    id: 'rev-002',
    productId: 'prod-003',
    productName: '얼그레이 마카롱 세트',
    userName: '이**',
    rating: 5,
    content: '선물용으로 구매했는데 포장도 예쁘고 마카롱도 정말 맛있었대요. 재구매 의사 100%입니다!',
    date: '2024-12-10',
  },
  {
    id: 'rev-003',
    productId: 'prod-006',
    productName: '피스타치오 크루아상',
    userName: '박**',
    rating: 5,
    content: '크루아상이 정말 겹겹이 바삭하고 피스타치오 크림이 고소하면서 달콤해요. 매일 먹고 싶은 맛!',
    date: '2024-12-08',
  },
  {
    id: 'rev-004',
    productId: 'prod-011',
    productName: '프리미엄 디저트 선물세트 A',
    userName: '최**',
    rating: 4,
    content: '크리스마스 선물로 보내드렸는데 정말 좋아하셨어요. 박스도 고급스럽고 하나하나 맛있었다고 합니다.',
    date: '2024-12-20',
  },
]

// 히어로 배너 슬라이드 데이터
export const heroSlides = [
  {
    id: 'slide-001',
    title: '달콤한 순간을\n선물하세요',
    subtitle: '프랑스 파티스리의 정통 레시피로 만든 프리미엄 디저트',
    buttonText: '전체 상품 보기',
    buttonLink: '/products',
    bgColor: 'bg-cream',
    image: '/images/hero-main.jpg',
  },
  {
    id: 'slide-002',
    title: '겨울 시즌\n한정 메뉴',
    subtitle: '따뜻한 겨울을 위한 특별한 디저트 컬렉션',
    buttonText: '시즌 메뉴 보기',
    buttonLink: '/products?category=cake',
    bgColor: 'bg-cream-dark',
    image: '/images/hero-winter.jpg',
  },
  {
    id: 'slide-003',
    title: '소중한 분께\n특별한 선물을',
    subtitle: '프리미엄 선물세트로 마음을 전하세요',
    buttonText: '선물세트 보기',
    buttonLink: '/products?category=gift',
    bgColor: 'bg-cream',
    image: '/images/hero-gift.jpg',
  },
]
